ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS coins INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS hunger INTEGER DEFAULT 100;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_hunger_update TIMESTAMP WITH TIME ZONE DEFAULT NOW();

NOTIFY pgrst, 'reload schema';
